conda_build:
  pkg_format: '2'
conda_forge_output_validation: false
exclusive_config_file: recipe/conda_build_config.yaml
github:
  user_or_org: kongexp
  repo_name: openmm-feedstock
  branch_name: main
  tooling_branch_name: main
github_actions:
  upload_packages: false
provider:
  linux_64: github_actions
  linux_aarch64: None
  linux_ppc64le: None
  osx_64: None
  osx_arm64: None
  win_64: None
test: native
workflow_settings:
  store_build_artifacts:
    - provider: github_actions
      platform: linux_64
      value: true
